name: SizeSpin
version: '1'
main: me.sizesmp.sizeSpin.Main
api-version: '1.21'
authors: [ SizeSMP ]
description: A plugin which gives you a chance to become bigger.. or smaller.
softdepend: [PlaceholderAPI]

commands:
  setsize:
    description: Set a player's size.
    usage: /setsize <size> <player>
    permission: sizespin.use
  sizespin:
    description: Spin, spin, spin away! :)
    usage: /sizespin <player>
    permission: sizespin.use
    aliases: [spin]
  sizespinreload:
    description: Reloads the config
    usage: /sizespinreload
    permission: sizespin.reload

permissions:
  sizespin.use:
    description: Allows to use /sizespin & /setsize.
    default: op
  sizespin.reload:
    description: Allows to use /sizespinreload.
    default: op
